# -*- coding: utf-8 -*-
"""MahilaSarthi.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BemiOzYvrHfgqTlQoIKh_XBtA2ra-69d
"""

!pip install -q langchain langchain-community google-generativeai faiss-cpu langchain-google-genai
!pip install -q langchain langchain-community transformers torch accelerate
import getpass
import os
from langchain.chains import ConversationChain
from langchain.memory import ConversationBufferMemory
from langchain.prompts import PromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI

os.environ["GOOGLE_API_KEY"] = getpass.getpass("Enter your Google API Key: ")

class WomenSafetyBot:
    def __init__(self):

        self.llm = ChatGoogleGenerativeAI(model="gemini-pro", temperature=0.7, google_api_key=os.environ["GOOGLE_API_KEY"])


        self.prompt = PromptTemplate(
            input_variables=["history", "input"],
            template="""
You are SAFE-Assist, a compassionate AI assistant dedicated to women's safety and support.

IMPORTANT GUIDELINES:
- Always prioritize user safety and provide immediate, practical help
- Be empathetic, supportive, and non-judgmental
- Provide verified emergency contacts and resources
- Suggest safety measures and precautions
- If situation seems critical, emphasize contacting local authorities immediately

Previous conversation:
{history}

User: {input}
SAFE-Assist:"""
        )


        self.memory = ConversationBufferMemory()


        self.conversation = ConversationChain(
            llm=self.llm,
            memory=self.memory,
            prompt=self.prompt,
            verbose=False
        )

        self.emergency_resources = {
            "india": {
                "police": "100",
                "women_helpline": "1091",
                "emergency": "112",
                "domestic_violence": "181"
            },
            "us": {
                "police": "911",
                "domestic_violence": "1-800-799-7233",
                "sexual_assault": "1-800-656-4673"
            },
            "uk": {
                "police": "999",
                "domestic_violence": "0808 2000 247"
            }
        }

    def get_emergency_contacts(self, country="india"):
        """Get emergency contacts for specific country"""
        contacts = self.emergency_resources.get(country.lower(), self.emergency_resources["india"])
        contact_text = "\n".join([f"• {key.replace('_', ' ').title()}: {value}" for key, value in contacts.items()])
        return f"Emergency Contacts ({country.upper()}):\n{contact_text}"

    def safety_tips(self):
        """Provide general safety tips"""
        tips = """
🔒 Important Safety Tips:
• Share your live location with trusted contacts
• Keep emergency numbers on speed dial
• Use well-lit, populated routes
• Trust your instincts - if something feels wrong, leave
• Have a safety app installed (like SafeCity, Raksha)
• Learn basic self-defense techniques
• Always check the backseat before entering your car
• Avoid sharing real-time location on social media
"""
        return tips

    def handle_query(self, user_input):
        """Process user query with safety prioritization"""
        user_lower = user_input.lower()

        # Check for emergency keywords
        emergency_keywords = ["emergency", "help", "danger", "threat", "attack", "unsafe", "stalk", "abuse", "violence"]

        if any(keyword in user_lower for keyword in emergency_keywords):
            immediate_response = "🚨 IMMEDIATE ACTION REQUIRED 🚨\n"
            immediate_response += "• Call your local police immediately\n"
            immediate_response += "• Contact trusted family/friends\n"
            immediate_response += "• Move to a safe, public location\n"
            immediate_response += "• Here are emergency contacts:\n"
            immediate_response += self.get_emergency_contacts()
            return immediate_response


        if "contact" in user_lower or "number" in user_lower or "helpline" in user_lower:
            return self.get_emergency_contacts()

        if "tip" in user_lower or "safety" in user_lower or "precaution" in user_lower:
            return self.safety_tips()


        try:
            response = self.conversation.predict(input=user_input)
            return response
        except Exception as e:
            return f"I'm here to help! For immediate assistance, please call emergency services. Error: {str(e)}"

print("Initializing SAFE-Assist Bot...")
safety_bot = WomenSafetyBot()


print("\n" + "="*60)
print("🚺 SAFE-ASSIST - Women Safety Helpline Bot")
print("="*60)
print("\nI'm here to provide safety information, emergency contacts, and support.")
print("Type 'quit' to exit the conversation.\n")


while True:
    user_input = input("You: ").strip()

    if user_input.lower() in ['quit', 'exit', 'bye']:
        print("SAFE-Assist: Stay safe! Remember, help is always available. 👋")
        break

    if user_input:
        response = safety_bot.handle_query(user_input)
        print(f"SAFE-Assist: {response}\n")

from langchain.llms import HuggingFaceHub
from langchain.chains import ConversationChain
from langchain.memory import ConversationBufferMemory
from langchain.prompts import PromptTemplate
import requests

class WomenSafetyBot:
    def __init__(self):
        try:
            from langchain_community.llms import HuggingFacePipeline
            from transformers import pipeline, AutoModelForCausalLM, AutoTokenizer

            model_name = "microsoft/DialoGPT-small"
            tokenizer = AutoTokenizer.from_pretrained(model_name)
            model = AutoModelForCausalLM.from_pretrained(model_name)

            pipe = pipeline(
                "text-generation",
                model=model,
                tokenizer=tokenizer,
                max_length=200,
                temperature=0.7,
                do_sample=True
            )

            self.llm = HuggingFacePipeline(pipeline=pipe)

        except Exception as e:
            print(f"Using backup model: {e}")
            self.llm = None

        self.emergency_resources = {
            "india": {
                "police": "📞 100",
                "women_helpline": "📞 1091",
                "emergency": "📞 112",
                "domestic_violence": "📞 181",
                "child_helpline": "📞 1098"
            },
            "us": {
                "police": "📞 911",
                "domestic_violence": "📞 1-800-799-7233",
                "sexual_assault": "📞 1-800-656-4673"
            },
            "uk": {
                "police": "📞 999",
                "domestic_violence": "📞 0808 2000 247"
            }
        }

        self.memory = ConversationBufferMemory()

    def get_emergency_contacts(self, country="india"):
        contacts = self.emergency_resources.get(country.lower(), self.emergency_resources["india"])
        contact_text = "\n".join([f"• {key.replace('_', ' ').title()}: {value}" for key, value in contacts.items()])
        return f"🚨 EMERGENCY CONTACTS ({country.upper()}):\n{contact_text}"

    def immediate_safety_guide(self):
        guide = """
🚨 IMMEDIATE SAFETY ACTIONS:

1. 🚓 CALL EMERGENCY SERVICES - Police: 100 (India) / 911 (US)
2. 📱 Contact trusted family/friends - Share your location
3. 📍 Move to a safe, public place with people
4. 🗣️ Draw attention - Make noise if threatened
5. 🏃‍♀️ Trust your instincts - Leave if uncomfortable

Remember: Your safety comes first!
"""
        return guide

    def safety_tips(self, situation=None):
        tips = {
            "transport": """
🚌 Public Transport Safety:
• Sit near the driver or in crowded areas
• Share your live location with trusted contacts
• Avoid isolated bus stops/stations
• Keep emergency numbers on speed dial
• Trust your instincts - change seats if uncomfortable
""",
            "walking": """
🚶‍♀️ Walking Safety:
• Use well-lit, populated routes
• Walk confidently with awareness
• Avoid using headphones in isolated areas
• Have your phone ready to call for help
• Share your ETA with someone
""",
            "general": """
🔒 General Safety Tips:
• Always trust your instincts
• Learn basic self-defense techniques
• Keep emergency contacts easily accessible
• Use safety apps (SafeCity, Raksha, etc.)
• Avoid sharing real-time location on social media
• Have a safety plan for different situations
"""
        }

        return tips.get(situation, tips["general"])

    def handle_query(self, user_input):
        user_lower = user_input.lower()

        emergency_keywords = ["emergency", "help", "danger", "threat", "attack", "unsafe", "stalk", "abuse", "violence", "stuck", "alone", "scared", "fear"]

        if any(keyword in user_lower for keyword in emergency_keywords):
            response = self.immediate_safety_guide()
            response += "\n" + self.get_emergency_contacts()
            return response

        if any(word in user_lower for word in ["bus", "train", "taxi", "transport", "vehicle"]):
            return self.safety_tips("transport") + "\n" + self.get_emergency_contacts()

        if any(word in user_lower for word in ["walk", "street", "road", "night"]):
            return self.safety_tips("walking") + "\n" + self.get_emergency_contacts()

        if any(word in user_lower for word in ["contact", "number", "helpline", "call"]):
            return self.get_emergency_contacts()

        if any(word in user_lower for word in ["tip", "safety", "precaution", "advice"]):
            return self.safety_tips("general")

        responses = {
            "hello": "👋 Hello! I'm SAFE-Assist, your women's safety helper. How can I assist you today?",
            "hi": "👋 Hi there! I'm here to provide safety information and support. What do you need help with?",
            "thank": "You're welcome! Stay safe and remember - help is always available when you need it. 💪",
            "help": "I'm here to help! Please tell me your situation so I can provide the right assistance.",
        }

        for key, response in responses.items():
            if key in user_lower:
                return response

        return f"""I understand you said: "{user_input}"

As your safety assistant, I can help you with:
• 🚨 Emergency contacts and immediate safety steps
• 🚌 Safety tips for public transport, walking, etc.
• 🔒 General safety precautions
• 📱 Resource information

Please tell me more about your situation so I can provide specific help!"""

print("🚺 Initializing SAFE-Assist Women Safety Bot...")
safety_bot = WomenSafetyBot()

print("\n" + "="*70)
print("🚺 SAFE-ASSIST - Women Safety Helpline Bot")
print("="*70)
print("\nI'm here to provide safety information, emergency contacts, and support.")
print("I can help with emergency situations, safety tips, and resources.")
print("Type 'quit' to exit the conversation.\n")

while True:
    user_input = input("You: ").strip()

    if user_input.lower() in ['quit', 'exit', 'bye']:
        print("\nSAFE-Assist: Stay safe! Remember, you're strong and help is always available. 👋")
        print("Emergency Contacts: Police: 100 | Women Helpline: 1091 | Emergency: 112")
        break

    if user_input:
        response = safety_bot.handle_query(user_input)
        print(f"\nSAFE-Assist: {response}\n")